import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Nav } from "@/components/Nav";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let cartId = cookies().get("cartId")?.value;

  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav cartId={cartId} />
        <div className="container my-6">{children}</div>
      </body>
    </html>
  );
}
