import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Nav } from "@/components/Nav";
import { cookies } from "next/headers";
import { getCartAction } from "@/components/cart/actions";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let cartId = cookies().get("cartId")?.value;
  if (!cartId) return null;
  let cart = await getCartAction(cartId);

  return (
    <html lang="en">
      <body>
        {children}
        {/* <Nav navCart={cart} /> */}
        {/* <div className="container my-6">{children}</div> */}
      </body>
    </html>
  );
}
